import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  ru: {
    // Navigation
    nav_home: "Главная",
    nav_create_fund: "Создать фонд",
    nav_leaderboard: "Лидеры",
    nav_faq: "FAQ",
    nav_profile: "Профиль",
    nav_admin_matches: "Управление матчами",
    // Sidebar
    your_balance: "Ваш баланс",
    points: "баллов",
    admin: "Админ",
    logout: "Выход",
    login: "Войти",
    // Home
    home_subtitle: "Английская Премьер-Лига • Пулы прогнозов",
    create_fund: "Создать фонд",
    balance: "Баланс",
    back_to_sports: "Назад к выбору спорта",
    loading: "Загрузка...",
    // Sport Selection
    sport_select_title: "Выберите вид спорта",
    sport_select_subtitle: "Соревнуйтесь с друзьями в прогнозах на матчи",
    coming_soon: "Скоро",
    // Gameweek
    quick_create: "Быстрое создание",
    gw_title: "Тур",
    matches: "матчей",
    // Open Funds
    open_funds: "Открытые фонды",
    no_funds: "Нет открытых фондов",
    join: "Присоединиться",
    players: "игроков",
    prize_pool: "Призовой фонд",
    entry: "Взнос",
    // FAQ
    faq_title: "FAQ & Правила",
    faq_subtitle: "Всё что нужно знать об игре",
    faq_support: "Остались вопросы?",
    faq_support_text: "Свяжитесь с нами через боковое меню",
    // Profile
    profile_title: "Профиль",
    total_balance: "Баланс",
    total_winnings: "Всего выиграно",
    total_wins: "Побед",
    participations: "Участий",
    // Common
    min: "мин",
    max: "макс",
    participants: "участников",
    private: "Приватный",
    public: "Публичный",
    status_open: "Открыт",
    status_closed: "Закрыт",
    status_finished: "Завершён",
    status_in_progress: "В процессе",
    status_cancelled: "Отменён",
    fund_details: "Детали фонда",
    leaderboard: "Таблица лидеров",
    my_predictions: "Мои прогнозы",
    join_fund: "Присоединиться к фонду",
    fund_closed: "Фонд закрыт",
    // Sport Selection extras
    sport_epl: "Английская Премьер-Лига",
    sport_epl_short: "АПЛ",
    sport_esports: "Киберспорт",
    sport_ucl: "Лига Чемпионов УЕФА",
    more_sports_coming: "Больше спортов и турниров добавляются в ближайшее время",
    // GameweekCard
    quick_create_fund: "Быстрое создание фонда",
    fund_name: "Название фонда",
    fund_name_hint: "Можете изменить название или оставить как есть",
    collapse: "Свернуть",
    continue_to_predictions: "Продолжить к прогнозам",
    matches_preselected: "Матчи и настройки уже выбраны",
    gameweek_card_hint: "12 кредитов • 10 матчей • 100 баллов взнос",
    // OpenFundsPreview
    show_all_funds: "Показать все открытые фонды",
    be_first_to_create: "Станьте первым, кто создаст пул прогнозов!",
    // FundCard
    joined: "Участвуете",
    view_details: "Смотреть детали",
    // Username modal
    choose_username: "Выберите имя пользователя",
    username_hint: "Это имя будет отображаться в таблице лидеров и фондах",
    username_placeholder: "имя пользователя",
    save: "Сохранить",
    username_min: "Имя пользователя должно быть не менее 3 символов",
    // FAQ
    faq_heading: "Часто задаваемые вопросы",
    faq_desc: "Всё что нужно знать о MatchFund Fantasy",
    faq_still_questions: "Остались вопросы?",
    faq_contact: "Свяжитесь с нами через кнопку обратной связи на боковой панели",
    faq_q1: "Какие типы прогнозов доступны?",
    faq_q1_p1: "На каждый матч вы можете сделать максимум 2 прогноза из следующих типов:",
    faq_q1_l1: "Исход матча (3 очка): Кто выиграет или ничья.",
    faq_q1_l2: "Обе забьют (2 очка): Да или Нет.",
    faq_q1_l3: "Количество голов (2.5 очка): 3+ голов или 0-2 гола.",
    faq_q1_l4: "Будет ли разгром (победа с разницей 3+ мячей)? (2.5 очка): Да или Нет.",
    faq_q1_l5: "Победа всухую (4 очка): Команда выиграет, не пропустив.",
    faq_q1_l6: "Точный счёт (9 очков): Угадайте точный итоговый счёт.",
    faq_q1_note: "Максимум 2 прогноза на матч • Общий лимит прогнозов = количество матчей + 2",
    faq_q2: "Сколько всего прогнозов я могу сделать?",
    faq_q2_p1: "Общее количество прогнозов зависит от количества матчей в фонде.",
    faq_q2_p2: "Формула: количество матчей + 2. Например, при 10 матчах вам доступно 12 прогнозов.",
    faq_q2_example: "Пример: 5 матчей → 7 прогнозов; 10 матчей → 12 прогнозов (макс 2 на матч)",
    faq_q3: "Можно ли делать несколько прогнозов на один матч?",
    faq_q3_p1: "Да! Но максимум 2 прогноза на матч.",
    faq_q3_p2: "Например: Исход матча (3 очка) + Обе забьют (2 очка) = 2 прогноза на матч.",
    faq_q3_tip: "💡 Стратегия: комбинируйте разные типы прогнозов для максимизации очков!",
    faq_q4: "Как распределяется призовой фонд?",
    faq_q4_p1: "Призовой фонд распределяется следующим образом:",
    faq_q4_l1: "7% комиссия платформы (на развитие сервиса)",
    faq_q4_l2: "1% бонус создателю фонда (за организацию)",
    faq_q4_l3: "92% призовой фонд делится между победителями",
    faq_q4_h2: "Как делятся 92% призового фонда:",
    faq_q4_d1: "1-3 участника: 100% победителю (1 место)",
    faq_q4_d2: "4-9 участников: 70% первому, 30% второму",
    faq_q4_d3: "10+ участников: 50% первому, 30% второму, 20% третьему",
    faq_q4_example: "Пример: 10 человек × 100 баллов = 1000 → 920 призовых → 1 место: 460, 2 место: 276, 3 место: 184",
    faq_q5: "Что происходит если не набралось минимум участников?",
    faq_q5_p1: "Если к началу первого матча в фонде меньше участников чем указано в min_participants:",
    faq_q5_l1: "Фонд автоматически отменяется",
    faq_q5_l2: "Всем участникам возвращается полный взнос (100%)",
    faq_q5_l3: "Никто не теряет деньги",
    faq_q6: "Когда закрываются прогнозы?",
    faq_q6_p1: "Прогнозы закрываются автоматически:",
    faq_q6_l1: "За 5 минут до начала первого матча в фонде",
    faq_q6_l2: "После этого новые игроки не могут присоединиться",
    faq_q6_l3: "Существующие участники не могут изменить свои прогнозы",
    faq_q6_warning: "⚠️ Успейте сделать прогнозы заранее!",
    // Profile
    my_profile: "Мой профиль",
    stats_subtitle: "Статистика и достижения",
    refresh: "Обновить",
    total_predictions: "Всего прогнозов",
    win_rate: "Процент побед",
    my_funds: "Мои фонды",
    active_tab: "Активные",
    finished_tab: "Завершённые",
    entry_paid: "Взнос",
    winnings: "Выигрыш",
    no_active_funds: "Нет активных фондов",
    find_fund: "Найти фонд",
    no_finished_funds: "Нет завершённых фондов",
    status_open_label: "Открыт",
    status_closed_label: "Закрыт",
    in_progress_label: "В процессе",
    winner_label: "Победа!",
    refunded_label: "Возврат",
    finished_label: "Завершён",
    // Leaderboard
    leaderboard_title: "Таблица лидеров",
    leaderboard_subtitle: "Лучшие игроки MatchFund Fantasy",
    wins: "побед",
    funds_count: "фондов",
    win_rate_pct: "побед",
    points_won: "баллов выиграно",
    no_participants_yet: "Еще не участвовал в фондах",
    no_users_yet: "Пока нет пользователей",
    player_default: "Игрок",
    // CreateFund
    back: "Назад",
    quick_create_title: "Быстрое создание фонда",
    create_new_fund: "Создать новый фонд",
    matches_auto_selected: "Матчи выбраны автоматически • Сделайте прогнозы",
    your_balance_label: "Ваш баланс",
    error_label: "Ошибка",
    fund_settings: "Настройки фонда",
    description_optional: "Описание (необязательно)",
    description_placeholder: "Опишите ваш фонд...",
    entry_fee_label: "Взнос",
    entry_fixed: "Фиксированный взнос",
    max_players: "Макс. игроков",
    private_fund: "Приватный фонд",
    private_fund_hint: "Доступен только по ссылке и паролю",
    password_label: "Пароль (4-6 цифр)",
    password_error: "Пароль должен содержать не менее 4 цифр.",
    password_hint: "💡 Поделитесь ссылкой и паролем с друзьями после создания",
    credit_system_info: "📊 Система кредитов: Вы получите 10-20 кредитов на 10 матчей. Максимум 2 прогноза на матч!",
    next_predictions: "Далее: Сделать прогнозы",
    distribute_credits: "Распределите 10-20 кредитов",
    credits_label: "кредитов",
    credits_min_warning: "⚠️ Минимум 10 кредитов (минимум 1 прогноз на матч)",
    credits_max_warning: "❌ Максимум 20 кредитов",
    unused_credits_info: "неиспользованных кредитов",
    unused_credits_bonus: "Стоят по 0.5 очка",
    bonus_points: "бонусных очков",
    credits_full: "Все кредиты распределены!",
    match_outcome: "Исход матча (3 очка):",
    draw: "Ничья",
    btts: "Обе забьют (2 очка):",
    yes: "Да",
    no: "Нет",
    goals: "Количество голов (2.5 очка):",
    over_goals: "3+ голов",
    under_goals: "0-2 гола",
    blowout: "Будет ли разгром (победа с разницей 3+ мячей)? (2.5 очка):",
    blowout_yes: "Да (разница 3+)",
    clean_sheet: "Победа всухую (4 очка):",
    clean_sheet_suffix: "всухую",
    exact_score: "Точный счёт (9 очков)",
    exact_score_remove: "❌ Убрать",
    exact_score_both: "⚠️ Введите оба счета",
    exact_score_confirmed: "✅ Ваш прогноз",
    create_fund_btn: "Создать фонд и отправить прогнозы",
    creating: "Создание...",
    used_of: "Использовано",
    of_two: "из 2",
    max_2_per_match: "Макс 2 прогноза на матч",
    max_2_tooltip: "Максимум 2 прогноза на матч",
    points_label: "баллов",
    if_correct: "очков если верно",
  },
  en: {
    // Navigation
    nav_home: "Home",
    nav_create_fund: "Create Fund",
    nav_leaderboard: "Leaderboard",
    nav_faq: "FAQ",
    nav_profile: "Profile",
    nav_admin_matches: "Manage Matches",
    // Sidebar
    your_balance: "Your balance",
    points: "points",
    admin: "Admin",
    logout: "Logout",
    login: "Login",
    // Home
    home_subtitle: "English Premier League • Prediction Pools",
    create_fund: "Create Fund",
    balance: "Balance",
    back_to_sports: "Back to sport selection",
    loading: "Loading...",
    // Sport Selection
    sport_select_title: "Select a Sport",
    sport_select_subtitle: "Compete with friends in match predictions",
    coming_soon: "Coming Soon",
    // Gameweek
    quick_create: "Quick Create",
    gw_title: "Gameweek",
    matches: "matches",
    // Open Funds
    open_funds: "Open Funds",
    no_funds: "No open funds",
    join: "Join",
    players: "players",
    prize_pool: "Prize Pool",
    entry: "Entry",
    // FAQ
    faq_title: "FAQ & Rules",
    faq_subtitle: "Everything you need to know about the game",
    faq_support: "Still have questions?",
    faq_support_text: "Contact us through the sidebar menu",
    // Profile
    profile_title: "Profile",
    total_balance: "Balance",
    total_winnings: "Total Winnings",
    total_wins: "Wins",
    participations: "Participations",
    // Common
    min: "min",
    max: "max",
    participants: "participants",
    private: "Private",
    public: "Public",
    status_open: "Open",
    status_closed: "Closed",
    status_finished: "Finished",
    status_in_progress: "In Progress",
    status_cancelled: "Cancelled",
    fund_details: "Fund Details",
    leaderboard: "Leaderboard",
    my_predictions: "My Predictions",
    join_fund: "Join Fund",
    fund_closed: "Fund Closed",
    // Sport Selection extras
    sport_epl: "English Premier League",
    sport_epl_short: "EPL",
    sport_esports: "Esports",
    sport_ucl: "UEFA Champions League",
    more_sports_coming: "More sports and tournaments coming soon",
    // GameweekCard
    quick_create_fund: "Quick Create Fund",
    fund_name: "Fund Name",
    fund_name_hint: "You can change the name or leave it as is",
    collapse: "Collapse",
    continue_to_predictions: "Continue to Predictions",
    matches_preselected: "Matches and settings already selected",
    gameweek_card_hint: "12 credits • 10 matches • 100 points entry",
    // OpenFundsPreview
    show_all_funds: "Show all open funds",
    be_first_to_create: "Be the first to create a prediction pool!",
    // FundCard
    joined: "Joined",
    view_details: "View Details",
    // Username modal
    choose_username: "Choose a username",
    username_hint: "This name will appear in the leaderboard and funds",
    username_placeholder: "username",
    save: "Save",
    username_min: "Username must be at least 3 characters",
    // FAQ
    faq_heading: "Frequently Asked Questions",
    faq_desc: "Everything you need to know about MatchFund Fantasy",
    faq_still_questions: "Still have questions?",
    faq_contact: "Contact us via the feedback button in the sidebar",
    faq_q1: "What prediction types are available?",
    faq_q1_p1: "For each match you can make up to 2 predictions from the following types:",
    faq_q1_l1: "Match outcome (3 pts): Who wins or a draw.",
    faq_q1_l2: "Both teams to score (2 pts): Yes or No.",
    faq_q1_l3: "Goals total (2.5 pts): 3+ goals or 0-2 goals.",
    faq_q1_l4: "Blowout (win by 3+ goals)? (2.5 pts): Yes or No.",
    faq_q1_l5: "Win to nil (4 pts): Team wins without conceding.",
    faq_q1_l6: "Exact score (9 pts): Predict the exact final score.",
    faq_q1_note: "Max 2 predictions per match • Total prediction limit = number of matches + 2",
    faq_q2: "How many total predictions can I make?",
    faq_q2_p1: "Your total prediction allowance depends on the number of matches in the fund.",
    faq_q2_p2: "Formula: number of matches + 2. For example, with 10 matches you get 12 predictions.",
    faq_q2_example: "Example: 5 matches → 7 predictions; 10 matches → 12 predictions (max 2 per match)",
    faq_q3: "Can I make multiple predictions on one match?",
    faq_q3_p1: "Yes! But max 2 predictions per match.",
    faq_q3_p2: "Example: Match outcome (3 pts) + BTTS (2 pts) = 2 predictions on the match.",
    faq_q3_tip: "💡 Strategy: combine different prediction types to maximise points!",
    faq_q4: "How is the prize pool distributed?",
    faq_q4_p1: "The prize pool is distributed as follows:",
    faq_q4_l1: "7% platform fee (for development)",
    faq_q4_l2: "1% bonus to the fund creator (for organizing)",
    faq_q4_l3: "92% prize pool split among winners",
    faq_q4_h2: "How is the 92% split:",
    faq_q4_d1: "1-3 participants: 100% to the winner (1st place)",
    faq_q4_d2: "4-9 participants: 70% to 1st, 30% to 2nd",
    faq_q4_d3: "10+ participants: 50% to 1st, 30% to 2nd, 20% to 3rd",
    faq_q4_example: "Example: 10 people × 100 pts = 1000 → 920 prize → 1st: 460, 2nd: 276, 3rd: 184",
    faq_q5: "What if the minimum participants isn't reached?",
    faq_q5_p1: "If the fund has fewer participants than min_participants when the first match starts:",
    faq_q5_l1: "The fund is automatically cancelled",
    faq_q5_l2: "All participants get a full refund (100%)",
    faq_q5_l3: "Nobody loses money",
    faq_q6: "When do predictions close?",
    faq_q6_p1: "Predictions close automatically:",
    faq_q6_l1: "5 minutes before the first match in the fund",
    faq_q6_l2: "After that, new players cannot join",
    faq_q6_l3: "Existing participants cannot change their predictions",
    faq_q6_warning: "⚠️ Make your predictions ahead of time!",
    // Profile
    my_profile: "My Profile",
    stats_subtitle: "Stats & Achievements",
    refresh: "Refresh",
    total_predictions: "Total Predictions",
    win_rate: "Win Rate",
    my_funds: "My Funds",
    active_tab: "Active",
    finished_tab: "Finished",
    entry_paid: "Entry",
    winnings: "Winnings",
    no_active_funds: "No active funds",
    find_fund: "Find a Fund",
    no_finished_funds: "No finished funds",
    status_open_label: "Open",
    status_closed_label: "Closed",
    in_progress_label: "In Progress",
    winner_label: "Winner!",
    refunded_label: "Refunded",
    finished_label: "Finished",
    // Leaderboard
    leaderboard_title: "Leaderboard",
    leaderboard_subtitle: "Top MatchFund Fantasy Players",
    wins: "wins",
    funds_count: "funds",
    win_rate_pct: "win rate",
    points_won: "points won",
    no_participants_yet: "Has not joined any funds yet",
    no_users_yet: "No users yet",
    player_default: "Player",
    // CreateFund
    back: "Back",
    quick_create_title: "Quick Create Fund",
    create_new_fund: "Create New Fund",
    matches_auto_selected: "Matches selected automatically • Make your predictions",
    your_balance_label: "Your balance",
    error_label: "Error",
    fund_settings: "Fund Settings",
    description_optional: "Description (optional)",
    description_placeholder: "Describe your fund...",
    entry_fee_label: "Entry Fee",
    entry_fixed: "Fixed entry fee",
    max_players: "Max players",
    private_fund: "Private fund",
    private_fund_hint: "Accessible only via link and password",
    password_label: "Password (4-6 digits)",
    password_error: "Password must be at least 4 digits.",
    password_hint: "💡 Share the link and password with friends after creation",
    credit_system_info: "📊 Credit system: You'll get 10-20 credits for 10 matches. Max 2 predictions per match!",
    next_predictions: "Next: Make Predictions",
    distribute_credits: "Distribute 10-20 credits",
    credits_label: "credits",
    credits_min_warning: "⚠️ Minimum 10 credits (at least 1 prediction per match)",
    credits_max_warning: "❌ Maximum 20 credits",
    unused_credits_info: "unused credits",
    unused_credits_bonus: "Worth 0.5 pts each",
    bonus_points: "bonus points",
    credits_full: "All credits distributed!",
    match_outcome: "Match outcome (3 pts):",
    draw: "Draw",
    btts: "Both teams to score (2 pts):",
    yes: "Yes",
    no: "No",
    goals: "Goals total (2.5 pts):",
    over_goals: "3+ goals",
    under_goals: "0-2 goals",
    blowout: "Blowout (win by 3+ goals)? (2.5 pts):",
    blowout_yes: "Yes (3+ difference)",
    clean_sheet: "Win to nil (4 pts):",
    clean_sheet_suffix: "to nil",
    exact_score: "Exact Score (9 pts)",
    exact_score_remove: "❌ Remove",
    exact_score_both: "⚠️ Enter both scores",
    exact_score_confirmed: "✅ Your prediction",
    create_fund_btn: "Create Fund & Submit Predictions",
    creating: "Creating...",
    used_of: "Used",
    of_two: "of 2",
    max_2_per_match: "Max 2 predictions per match",
    max_2_tooltip: "Maximum 2 predictions per match",
    points_label: "points",
    if_correct: "points if correct",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("app_language") || "ru";
  });

  const toggleLanguage = () => {
    const newLang = language === "ru" ? "en" : "ru";
    setLanguage(newLang);
    localStorage.setItem("app_language", newLang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["ru"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}